name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: aarnott/nbgv@master
    - run: echo "VERSION= $NBGV_Version"
      
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Build with dotnet
      run: | 
        dotnet tool install -g nbgv
        dotnet build --configuration Release
