name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Nerdbank.GitVersioning
      uses: AArnott/nbgv@v0.3
      with:
        setAllVars: true
    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"

    - name: Build with dotnet
      run: dotnet build --configuration Release
    
  publish:

    name: Publish packages to NuGet 

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Publish
      - name: Publish Jboyer87.ApiClient.Utilities to NuGet 
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ApiClient.Utilities/ApiClient.Utilities.csproj
          # Filepath containing version info, relative to root of repository. Defaults to `PROJECT_FILE_PATH` if not specified
          VERSION_FILE_PATH: .
          # Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
          VERSION_STATIC: $NBGV_SemVer2
          TAG_COMMIT: false
          # API key for the NuGet feed
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # NuGet package name, required when it's different from the project name
          PACKAGE_NAME: Jboyer87.ApiClient.Utilities

      - uses: actions/checkout@v2
      
      # Publish
      - name: Publish Jboyer87.ApiClient to NuGet 
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ApiClient.Common/ApiClient.Common.csproj
          # Filepath containing version info, relative to root of repository. Defaults to `PROJECT_FILE_PATH` if not specified
          VERSION_FILE_PATH: .
          # Bypasses version resolution; useful for external providers like Nerdbank.GitVersioning
          VERSION_STATIC: $NBGV_SemVer2
          TAG_COMMIT: false
          # API key for the NuGet feed
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # NuGet package name, required when it's different from the project name
          PACKAGE_NAME: Jboyer87.ApiClient

      - name: Publish Packages
        shell: bash
        run: |
          dotnet nuget push /home/runner/work/ApiClient/ApiClient/ApiClient.Common.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
          dotnet nuget push /home/runner/work/ApiClient/ApiClient/ApiClient.Utilities.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}